title: Yoel Cabo
markdown: kramdown
url: "https://yoel.cat"

# for atom feed
author:
  name: Yoel Cabo
  email: ei@yoel.cat

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
